In [1]:
mylist = [1,2,3]

In [2]:
mylist

[1, 2, 3]

In [3]:
type(mylist)

list

In [1]:
import numpy as np

In [10]:
np.array(mylist)

array([1, 2, 3])

In [11]:
myarray = np.array(mylist)

In [12]:
myarray

array([1, 2, 3])

In [13]:
type(myarray)

numpy.ndarray

In [14]:
my_matrix = [[1,2,3],[4,5,6], [7,8,9]]

In [15]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10)

#like range up to not including

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,100,5)


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.zeros((3,5))

#rows first colomns second

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.linspace(0,10,3)

#from 0 to 10 (10 includes) 3 numbers equally divided

array([ 0.,  5., 10.])

In [7]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [8]:
len(np.linspace(1,100,20))

20

In [9]:
np.eye(5)

#identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(1)

#random distrubition

array([0.25307222])

In [11]:
np.random.rand(1)

array([0.93929601])

In [12]:
np.random.rand(5)

array([0.0259489 , 0.0974416 , 0.24584715, 0.24024936, 0.43100044])

In [13]:
np.random.rand(3,4)

array([[0.12297035, 0.34334129, 0.95585542, 0.92566905],
       [0.1100673 , 0.5189194 , 0.91740238, 0.32339164],
       [0.75563144, 0.29486826, 0.51301631, 0.33540839]])

In [16]:
np.random.randn(10)

#standart normal distribution

array([ 1.17168138, -0.35895206,  1.71833937, -0.30305158, -0.35398664,
       -0.8109769 ,  0.34519813,  0.87109728, -0.04234632, -0.63363431])

In [17]:
np.random.randn(2,4)

array([[ 1.54728448, -0.3370212 , -0.98186101, -0.72644742],
       [-1.04249748,  0.17138927, -0.75071277,  0.13175979]])

In [19]:
np.random.randint(0,101,5)

array([66, 76, 97, 17, 45])

In [21]:
np.random.randint(0,101,(4,5))

array([[ 79,  26,  71,  86,  20],
       [ 56,  53,  35, 100,  24],
       [  9,  17,  24,  73,  46],
       [ 28,  78,  49,  20,  32]])

In [22]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
np.random.seed(2)
np.random.rand(4)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239])

In [24]:
np.random.seed(2)
np.random.rand(4)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239])

In [25]:
np.random.rand(4)

array([0.4203678 , 0.33033482, 0.20464863, 0.61927097])

In [26]:
arr = np.arange(0,25)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [30]:
arr.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

In [31]:
ranarr = np.random.randint(0,101,10)

In [32]:
ranarr

array([63, 31, 90, 20, 37, 39, 67,  4, 42, 51])

In [33]:
ranarr.max()

90

In [34]:
ranarr.min()

4

In [36]:
ranarr.argmax()

#index location

2

In [37]:
ranarr.argmin()

7

In [39]:
ranarr.dtype

dtype('int32')

In [38]:
arr.reshape

dtype('int32')

In [2]:
arr

NameError: name 'arr' is not defined

In [41]:
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)

In [4]:
arr = np.arange(0,25)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
arr.reshape(25,1).shape

(25, 1)

In [11]:
arr.dtype

dtype('int32')

In [48]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [13]:
arr2 = np.array([.2,4.3])

In [14]:
arr2

array([0.2, 4.3])

In [15]:
arr2.dtype

dtype('float64')